name: "versioning"

on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - dev
      - main
    # - 'release/**'
    # - 'hotfix/**'

env:
  GITVERSION: "gittools/gitversion:5.10.0-alpine.3.14-6.0"
  PROD_BRANCH: "main"
  TEST_BRANCH: "dev"
  MAIN_BRANCHES: ("dev" "main")
  GITVERSION_TAG_PROPERTY_PULL_REQUESTS: .SemVer
  GITVERSION_TAG_PROPERTY_DEFAULT: .SemVer
  GITVERSION_TAG_PROPERTY_DEVELOP: .SemVer
  GITVERSION_TAG_PROPERTY_RELEASE: .SemVer
  GITVERSION_TAG_PROPERTY_HOTFIX: .SemVer
  GITVERSION_TAG_PROPERTY_MAIN: .MajorMinorPatch
  GITVERSION_REPO_TYPE: SINGLE_APP
  GITVERSION_CONFIG_SINGLE_APP: "/repo/.cicd/common/.gitversion.yml"
  GITVERSION_CONFIG_MONOREPO: "/repo/apps/${svc}/.gitversion.yml"

jobs:
  gitversion:
    name: gitversion
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: |
          git fetch --unshallow
          git checkout main && git checkout -
          git checkout dev && git checkout -

      - name: Checkout to branch
        run: . ./.cicd/gitversion.sh checkout

      - name: Calculate changed services
        id: calculate_changed_services
        run: . ./.cicd/gitversion.sh changed

      - name: Calculate versions
        id: calculate_service_versions
        env:
          SEMVERYEASY_CHANGED: ${{ steps.calculate_changed_services.outputs.changed }}
          SEMVERYEASY_CHANGED_SERVICES: ${{ steps.calculate_changed_services.outputs.changed_services }}
        run: . ./.cicd/gitversion.sh calculate-version

      - name: Update PR description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEMVERY_YEASY_PR_BODY: ${{ steps.calculate_service_versions.outputs.PR_BODY }}
        if: ${{ github.event_name == 'pull_request' }}
        run: . ./.cicd/gitversion.sh update-pr

      - name: Tag build
        if: ${{ github.event_name == 'push' && (startsWith(steps.calculate_changed_services.outputs.diff_dest, 'release') || startsWith(steps.calculate_changed_services.outputs.diff_dest, 'hotfix') || contains(env.MAIN_BRANCHES, steps.calculate_changed_services.outputs.diff_dest)) }}
        id: tag_build
        env:
          DIFF_DEST: ${{ steps.calculate_changed_services.outputs.DIFF_DEST }}
          SEMVERYEASY_CHANGED: ${{ steps.calculate_changed_services.outputs.changed }}
          SEMVERYEASY_CHANGED_SERVICES: ${{ steps.calculate_changed_services.outputs.changed_services }}
        run: . ./.cicd/gitversion.sh tag
